### PR TITLE
Support 'ZZ_MODULES_PATH' environment variable value in module search path

### LINKED ISSUE #37: Allow search path to be extended with environment variable
Hi @aep,

What are your thoughts on allowing one the ability to add a path to the [search paths](https://github.com/aep/zz/blob/master/src/lib.rs#L86) `HashSet` with an environment variable? This could allow users to specify the location of their modules if they are not located in [standard directories](https://github.com/aep/zz/blob/master/src/lib.rs#L87-L96) when running `zz`:

```sh
$ ZZ_PATH=./path/to/modules zz build
```

I think something like:

```rust
if let Ok(zz_path) = std::env::var("ZZ_MODULES_PATH") {
	let module_paths = zz_path.split(":");
	for path in module_paths {
		searchpaths.insert(std::path::Path::new(&path).to_path_buf());
	}
} 
```

### PR DESCRIPTION
**Pull request by jwerle**
Fixes #37

### CODE REVIEW

**Comment by jwerle** [comment]
Should the goal be to treat the environment variable like the `PATH` environment variable?

**Comment by aep** [comment]
yeah that would make sense

**Comment by jwerle** [comment]
@aep Great, I just pushed a change that uses `ZZ_PATH` instead of `ZZ_MODULES_DIR` and treats that environment variable like the `PATH` environment variable

**Comment by jwerle** [comment]
@aep does `ZZ_MODULES_PATH` work?

**Comment by aep** [comment]
More importantly, does colon work on windows? I think PATH uses semicolon there, but I don't know why

**Comment by jwerle** [comment]
@aep A colon does not work on Windows. I updated the PR to support Windows with the correct delimiter (`;`)

**Comment by aep** [comment]
lgtm
no idea why ci failed

**Pull request merged**
